spring:
  application:
    name: gateway
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: user_route
          #uri: http://localhost:9999/
          uri: lb://users  #lb代表转发后台服务使用负载均衡，user代表服务注册中心上的服务名
          predicates:
            - Path=/feign/**

        - id: product_route
          #uri: http://localhost:9998/
          uri: lb://products
          predicates:
            - Path=/product/**
            - After=2020-08-06T20:11:00.000+08:00[Asia/Shanghai]
#          filters:
#            - AddRequestParameter=id,23
      discovery:
        locator:
          enabled: true   #开启根据服务名动态获取路由地址

server:
  port: 8989


management:
  endpoints:
    web:
      exposure:
        include: "*"  #开启所有web端点暴露




